<?
// UNCOMMENT BELOW TO USE DEFAULT APPLICATION SETTINGS FOR THE APP YOU WANT TO MAKE
//define('IS_FACEBOOK_GAME', TRUE);
//define('IS_DAILY_DEAL_AGGREGRATOR', TRUE);
//define('IS_BLOG', TRUE);

define('GLOBAL_LOGGING', TRUE);
define('GLOBAL_PRODUCTION', TRUE);
define('CREATE_CLEAN_LOGS', TRUE);
define('USE_MYSQL', TRUE);
define('USE_STATIC_METHODS', TRUE);
define('ENABLE_BROUNIT_TESTING', TRUE);
define('AUTO_SESSION_STORE', TRUE);
